### PR TITLE
Universal binding

### PR DESCRIPTION
**Pull request by cbizon**
There are a few approaches to universal binding (agreeing on the granularity of results):
1. Group edges as much as possible into the same result
2. Split edges as much as possible into different results
3. something inbetween... but it's hard to make an inbetween thing precise.

This PR chooses (1).

### CODE REVIEW

**Review by edeutsch — COMMENTED** [review]
I've read the proposed sentence several times, and I cannot see how it means what I think we want it to mean. I think what we want is for each result to contain all paths between the source node and each final target node, right? No final target node should appear in two different results? Is that what we're trying to say?

**Comment by cbizon** [comment]
Thanks @edeutsch .  [Here](https://docs.google.com/presentation/d/1Ecxj2Eiy-dIEx4ax3pNyov2oSszMtxXDOHTceEOqmDg/edit#slide=id.g133a7bafd80_0_173) are some slides that explain more fully what I mean.

**Comment by edeutsch** [comment]
I agree on the concept. I like it. I just don't think the PR text captures what we want to require. I suspect it will be especially confusing for those that don't already understand the concept.

**Comment by cbizon** [comment]
>> For a given set of node bindings, there can be only a single result.

> I think I understand what you're trying to say, but I don't think this says it. This says that there shouldn't be two identical results with exactly the same node bindings, which is true and obvious.

It may be true, but it's not obvious in the sense that not everybody is doing it that way :) 

> If a query has a clear essence query node (e.g., "drugs" in "which drugs treat disease X"), then
within a set of results, each essence knowledge graph node MUST only appear in a single result,
and all stated paths to that node MUST be included within that result.

I don't like the idea of an essence node unless we define it in trapi.  Also, I think that the effect of this statement is the same as "For a given set of node bindings, there can be only a single result." as long as we understand node bindings to be to the original qnodes.  So I don't think it's necessary to introduce that concept?

> I don't think this should be within the same enumerated point, because this is an entirely different concept than the above. This should be a subsequent point number 3 if there is a consensus on this. 

Agreed.  Part of the goal of this PR is to get consensus on this point in one way or the other...

**Review by edeutsch — CHANGES_REQUESTED** [review]
I will formally again disagree with "ARAs may include node and edges that do not bind to query_graph nodes". After discussion with the RTX team, we think this does a disservice to clients trying to interpret the data. If we are formally outvoted on this, that's fine, but I think we feel strongly enough that we won't just wave it through.

**Comment by andrewsu** [comment]
I agree that there shouldn't be two results with the same set of node bindings, so I agree on _"An ARA result is defined by the bindings of knowledge graph nodes to query graph nodes.  For a given set of node bindings, there can be only a single result."_

As for the last sentence -- whether there can be _extra_ node bindings beyond nodes in the query_graph -- perhaps we need three `knowledge_type`s on queries?

1. **strict mode** where no extra node bindings are allowed and all results conform to the explicitly stated query topology
2. **permissive mode** where extra node bindings are permitted to support a result that conforms to the explicitly stated query topology
3. **creative/inferred mode** where the query topology is explicitly one-hop, and results can be of any query topology

But such a solution would clearly need more discussion on one of our calls.  As to the PR as it's written (where "strict mode" and "permissive mode" are indistinguishable), I agree with @edeutsch that this will be confusing to downstream clients.

**Comment by cbizon** [comment]
OK, I've removed the controversial section until we can have further discussion.  As a preview, [here](https://docs.google.com/presentation/d/1e0npmXWCFaXIcBR31FG6ncfPhcur9g8cY0gk8TFbmEk/edit#slide=id.p) are some slides that lay out a few options.

It sounds like there's no pushback on the basic idea of agreeing to everybody binding in the same way (universal binding) at the level of original qgraph node bindings, so please review the modified text.

**Review by edeutsch — APPROVED** [review]
I agree with this.

I am thinking that it would be clearer to add "Two separate Results MUST NOT differ only in their edge bindings, with the same set of node bindings." This explicitly states what is implied that we want to disallow by the original statement, but might be missed by a non-careful reading and/or someone not very familiar with the schema. But I don't feel strongly about this.

**Review by newgene — APPROVED** [review]

**Review by CaseyTa — APPROVED** [review]

**Review by andrewsu — APPROVED** [review]

**Review by dkoslicki — COMMENTED** [review]
Agreed with Eric's suggestion to make the intent explicit: "Two separate Results MUST NOT differ only in their edge bindings, with the same set of node bindings."

**Comment by cbizon** [comment]
I've added Eric's suggestion as well.

**Review by dkoslicki — APPROVED** [review]

**Review by bill-baumgartner — APPROVED** [review]

**Pull request merged**
