### PR TITLE
edge merge

### PR DESCRIPTION
**Pull request by cbizon**

### CODE REVIEW

**Review by kennethmorton — APPROVED** [review]

**Review by vdancik — APPROVED** [review]

**Review by CaseyTa — APPROVED** [review]

**Review by ehinderer — APPROVED** [review]

**Review by edeutsch — APPROVED** [review]

**Comment by edeutsch** [comment]
So one complication with this:
```
When an ARA obtains multiple edges with the same subject, predicate, qualifiers, object, and original source from KPs, it should represent these as a single edge in the knowledge_graph component of a ReasonerAPI message.
```

In the RTX-KG2 knowledge graph, some identical edges are already merged in the knowledge graph and these are reported with multiple sources. For example, see the related_to edge in this result: https://arax.ncats.io/?r=41651
image
image

What is the merging policy when merging this edge with a edge from a different KP that only has one of the 3 knowledge sources, say.
Also, here we use three separate attributes, but it really could have been a single attribute with a list of 3 original sources.
Thoughts on that? Should we clarify in the language to guide implementation?

**Comment by edeutsch** [comment]
okay, thanks. Also tagging @saramsey since this impacts RTX-KG2.

**Comment by edeutsch** [comment]
At the risk of seeming overly pedantic, should we replace "original source" with "primary source" in the PR?

**Comment by cbizon** [comment]
@edeutsch I made a little change "original"->"original/primary".  Each edge should have one or the other only - My understanding is that the EPC group is probably going to remove one or the other (and then every edge should have that one), but I don't know which one is going to stick around.

**Review by bill-baumgartner — APPROVED** [review]

**Pull request merged**
