### PR TITLE
Response for node inference

### PR DESCRIPTION
**Pull request by cbizon**
Based on slack poll responses.

### CODE REVIEW

**Review by patrickkwang — APPROVED** [review]

**Review by vdancik — APPROVED** [review]

**Review by edeutsch — APPROVED** [review]

**Comment by andrewsu** [comment]
Just to confirm, this PR is meant to reflect what is graphically shown on slide 4 here? https://docs.google.com/presentation/d/1FrAVxIqwrpqlTrcRkdvhRFG9Tysw9o2XPAk6SiL11aE/edit#slide=id.gd577682d07_0_0

**Review by webyrd — APPROVED** [review]

**Comment by suihuang-ISB** [comment]
same  question as @andrewsu. The SLACK survey options mapping to the slides was not entirely clear because slide 3 is part of the problem description, and NOT one of the proposed solutions which start with slide 4.  (Slide 3 could also be one solution albeit not ideal, if admitting fuzzy mapping, right?)

**Comment by cbizon** [comment]
Yes, the text is meant to correspond to figure 4.  If that's not clear, then perhaps the wording could be clarified?    Or maybe we need to include some example queries and responses for this section?

**Comment by andrewsu** [comment]
For posterity, this is a screenshot from the slides that shows a graphical representation of what this PR is meant to express.

image

**Review by andrewsu — APPROVED** [review]
I approve the message, though I did create this PR in an attempt to make the behavior more explicit: https://github.com/NCATSTranslator/TranslatorArchitecture/pull/61

**Comment by cbizon** [comment]
Thanks @andrewsu I think that's nicer...

**Review by bill-baumgartner — APPROVED** [review]
I approve. There is a small typo in the new text however. "must present and linked" should be "must **be** present and linked"

**Review by sierra-moxon — APPROVED** [review]

**Review by CaseyTa — APPROVED** [review]

**Review by newgene — APPROVED** [review]

**Review by edeutsch — APPROVED** [review]

**Pull request merged**
